### ISSUE TITLE
Memes puffern

### ISSUE THREAD

**Issue by mainy1995** [mainy1995/MemeHub-Bot#19]
in einem bestimmten zeitraum nur ein  meme schicken

**Comment by bertye** [comment]
Damit nicht so viel gespammt wird, oder wie?

**Comment by mainy1995** [comment]
ja dachte dass halt regelmäßig was kommt, nicht 8 auf einmal von einem typen ka, feedback war aber nciht so gut habe ich in erinnerung

**Comment by bertye** [comment]
Hmm muss man sich nochmal gedanken drüber machen. Finde ich eigentlich nicht verkehrt

**Comment by mainy1995** [comment]
durch tokens gelöst
