### ISSUE TITLE
Kategorie Ändern / Setzen / Mehrere Kategorieen

### ISSUE THREAD

**Issue by bertye** [mainy1995/MemeHub-Bot#36]
Wir wollen in der lage sein, die Kategorie eines memes zu ändern. Außerdem wir über die Möglichkeit mehrerer Kategorien für ein Meme nachgedacht. Da beides eng miteinander zusammenhängt, sollten wir uns vor der umsetzung klar werden, was genau wir wollen.

**Comment by mainy1995** [comment]
Umgestzt
